from __future__ import annotations

"""Fashion / outfit image generation via MiniMax — Harper's Bazaar editorial look."""

import base64
import logging
import re

import httpx

from app.config import get_settings
from app.models.outfit_schemas import OutfitAsset
from app.providers.media_utils import (
    ensure_cover_size,
    new_asset_id,
    project_dir,
)
from app.providers.minimax_media import (
    DEFAULT_BASE,
    DEFAULT_IMAGE_MODEL,
    _check_base_resp,
    _minimax_api_key,
    _minimax_base,
)
from app.runtime_config import runtime_config

logger = logging.getLogger(__name__)

# 3:4 竖版（宽×高）；长边 1584 → 1188×1584
OUTFIT_SIZE = (1188, 1584)
OUTFIT_SIZE_LABEL = "1188x1584"

# 人物特征固化；画面气质改为芭莎杂志大片
_PROMPT_TEMPLATE = (
    "Harper's Bazaar 时尚杂志大片，高级时装编辑摄影，封面级质感；"
    "亚洲女性模特，20–25岁，标准全身站立或杂志摆姿，"
    "脸型流畅柔和的方圆脸，标准三庭五眼比例，颌面平整流畅，"
    "小巧精致鼻头，眉眼舒展自然，唇形饱满唇峰清晰，下颌线干净柔和；"
    "原生细腻哑光皮肤，保留自然皮肤肌理，无假面塑胶感，神态冷艳松弛有气场，{hairstyle}；"
    "身着{outfit}，搭配{accessories}；"
    "拍摄场景：{scene}；灯光：{lighting}；风格基调：{style_vibe}；"
    "中远景全身或四分之三身构图，竖版3:4构图，"
    "影棚/外景时尚大片光影，衣料质感与褶皱清晰，背景虚化有空间感，"
    "杂志印刷级色彩与对比度，高级时装摄影，8K高清写实，"
    "画面干净无任何文字、无杂志刊名、无水印、无AI标识、无logo、无角标。"
)

_NEGATIVE = (
    "禁止：手部畸形、多指、缺指、五官扭曲、脸部错位、凸嘴瘪嘴、严重法令凹陷、"
    "过度磨皮、塑料假脸、夸张畸形身材、比例失调、画面模糊、水印、文字、刊名、"
    "畸形肢体、怪异手指、画质崩坏、浓重网红美颜滤镜、廉价自拍感、"
    "AI字样、AI标识、AI生成、AIGC、generated by、watermark、logo、角标、字幕"
)


def build_fashion_prompt(
    *,
    hairstyle: str,
    outfit: str,
    accessories: str,
    scene: str,
    lighting: str,
    style_vibe: str = "芭莎封面大片",
    style_brief: str = "",
) -> str:
    brief = (style_brief or "高级时尚杂志编辑大片").strip()
    body = _PROMPT_TEMPLATE.format(
        hairstyle=(hairstyle or "精致大波浪或丝滑黑长直发，发丝有光泽").strip(),
        outfit=(outfit or "高级时装造型，廓形利落").strip(),
        accessories=(accessories or "设计师手袋、金属耳饰与细项链").strip(),
        scene=(scene or "都市玻璃幕墙前").strip(),
        lighting=(lighting or "时尚大片侧光与轮廓光").strip(),
        style_vibe=(style_vibe or "芭莎封面大片").strip(),
    )
    # Inject style brief near the front for stronger adherence
    body = f"风格要点：{brief}。{body}"
    prompt = f"{body} {_NEGATIVE}"
    return re.sub(r"\s+", " ", prompt).strip()[:1500]


def _asset_url(project_id: str, asset_id: str) -> str:
    return f"/api/outfits/{project_id}/assets/{asset_id}"


async def generate_fashion_image(
    *,
    project_id: str,
    index: int,
    image_prompt: str,
    day_label: str,
) -> OutfitAsset:
    api_key = _minimax_api_key()
    cfg = runtime_config.get()
    model = (cfg.image_model or DEFAULT_IMAGE_MODEL).strip() or DEFAULT_IMAGE_MODEL
    if not model.startswith("image-"):
        model = DEFAULT_IMAGE_MODEL
    try:
        base = _minimax_base()
    except Exception:  # noqa: BLE001
        base = DEFAULT_BASE

    prompt = re.sub(r"\s+", " ", (image_prompt or "").strip())[:1500]
    if not prompt:
        raise RuntimeError("穿搭提示词为空")

    settings = get_settings()
    body = {
        "model": model,
        "prompt": prompt,
        "aspect_ratio": "3:4",
        "response_format": "base64",
        "n": 1,
        "prompt_optimizer": True,
    }

    async with httpx.AsyncClient(timeout=180.0, follow_redirects=True) as client:
        res = await client.post(
            f"{base}/v1/image_generation",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=body,
        )
        if res.status_code >= 400:
            raise RuntimeError(f"MiniMax 生图失败 ({res.status_code}): {res.text[:400]}")
        data = res.json()
        _check_base_resp(data)

        payload = data.get("data") or {}
        asset_id = new_asset_id()
        filename = f"outfit_{index:02d}_{asset_id}.png"
        path = project_dir(settings, f"outfits/{project_id}") / filename

        b64_list = payload.get("image_base64") or []
        urls = payload.get("image_urls") or []
        if b64_list:
            raw_b64 = b64_list[0]
            if "," in raw_b64[:80]:
                raw_b64 = raw_b64.split(",", 1)[1]
            path.write_bytes(base64.b64decode(raw_b64))
        elif urls:
            img = await client.get(urls[0])
            if img.status_code >= 400:
                raise RuntimeError(f"下载 MiniMax 图片失败 ({img.status_code})")
            path.write_bytes(img.content)
        else:
            raise RuntimeError("MiniMax 生图返回中无图片数据")

    ensure_cover_size(path, OUTFIT_SIZE)
    return OutfitAsset(
        id=asset_id,
        kind="image",
        filename=filename,
        mime_type="image/png",
        url=_asset_url(project_id, asset_id),
        meta={
            "path": str(path),
            "index": index,
            "day_label": day_label,
            "model": model,
            "provider": "minimax",
            "aspect": "3:4",
            "size": OUTFIT_SIZE_LABEL,
        },
    )
